services:
  pb:
    container_name: pb
    image: ghcr.io/muchobien/pocketbase:latest
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - /var/lib/pb:/var/lib/pb
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
